apiVersion: v1
kind: Template
metadata:
  name: mq-resources
parameters:
- name: KAFKA_VOL_SIZE
  description: Size of volumes for Kafka brokers
  value: 250Gi
- name: KAFKA_VERSION
  description: kafka version
  value: 2.7.0
- name: ZK_VOL_SIZE
  description: Size of volumes for Zookeeper nodes
  value: 50Gi
- name: KAFKA_CPU_REQUESTS
  value: 250m
- name: KAFKA_CPU_LIMITS
  value: '1'
- name: KAFKA_MEMORY_REQUESTS
  value: 4Gi
- name: KAFKA_MEMORY_LIMITS
  value: 5Gi
- name: KAFKA_NUM_REPLICAS
  value: '3'
- name: KAFKA_HEAP_OPTS_XMS
  value: 4g
- name: KAFKA_HEAP_OPTS_XMX
  value: 4g
- name: ZOOKEEPER_CPU_REQUESTS
  value: 250m
- name: ZOOKEEPER_CPU_LIMITS
  value: '1'
- name: ZOOKEEPER_MEMORY_REQUESTS
  value: 4Gi
- name: ZOOKEEPER_MEMORY_LIMITS
  value: 5Gi
- name: ZOOKEEPER_NUM_REPLICAS
  value: '3'
- name: READY_DELAY
  value: '15'
- name: READY_TIMEOUT
  value: '5'
- name: READY_PERIOD
  value: '10'
- name: READY_THRESHOLD
  value: '3'
- name: AUTH_TYPE
  value: 'scram-sha-512'

objects:
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaUser
  metadata:
    labels:
      app: platform-mq
      strimzi.io/cluster: platform-mq
    name: kafka-user-all 
  spec:
    authentication:
      type: ${AUTH_TYPE} 
      password:
        valueFrom:
          secretKeyRef:
            name: kafka-user-all
            key: password
    authorization:
      acls:
        - host: '*'
          operation: All
          resource:
            name: '*'
            patternType: literal
            type: topic
        - host: '*'
          operation: All
          resource:
            name: '*'
            patternType: literal
            type: group
      type: simple

- apiVersion: kafka.strimzi.io/v1beta2
  kind: Kafka
  metadata:
    name: platform-mq
    labels:
      app: platform-mq
  spec:
    entityOperator:
      tlsSidecar:
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      topicOperator:
        jvmOptions:
          javaSystemProperties:
          - name: log4j2.formatMsgNoLookups
            value: "true"
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
      userOperator:
        jvmOptions:
          javaSystemProperties:
          - name: log4j2.formatMsgNoLookups
            value: "true"
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
    kafka:
      version: ${KAFKA_VERSION}
      authorization:
        type: simple
      config:
        auto.create.topics.enable: false
        log.retention.hours: 24
        offsets.topic.replication.factor: 3
        transaction.state.log.min.isr: 2
        transaction.state.log.replication.factor: 3
        num.recovery.threads.per.data.dir: 3
      jvmOptions:
        -Xms: ${KAFKA_HEAP_OPTS_XMS}
        -Xmx: ${KAFKA_HEAP_OPTS_XMX}
      listeners:
      - name: plain
        type: internal
        port: 9092
        tls: false
      - name: tls
        type: internal
        port: 9093
        tls: true
        authentication:
          type: scram-sha-512
      livenessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            name: kafka-metrics
            key: kafka-metrics-config.yml
      readinessProbe:
        initialDelaySeconds: ${{READY_DELAY}}
        timeoutSeconds: ${{READY_TIMEOUT}}
        periodSeconds: ${{READY_PERIOD}}
        failureThreshold: ${{READY_THRESHOLD}}
      replicas: ${{KAFKA_NUM_REPLICAS}}
      resources:
        limits:
          cpu: ${KAFKA_CPU_LIMITS}
          memory: ${KAFKA_MEMORY_LIMITS}
        requests:
          cpu: ${KAFKA_CPU_REQUESTS}
          memory: ${KAFKA_MEMORY_REQUESTS}
      storage:
        deleteClaim: false
        size: ${KAFKA_VOL_SIZE}
        type: persistent-claim
    zookeeper:
      livenessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      readinessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            name: kafka-metrics
            key: zookeeper-metrics-config.yml
      replicas: ${{ZOOKEEPER_NUM_REPLICAS}}
      resources:
        limits:
          cpu: ${ZOOKEEPER_CPU_LIMITS}
          memory: ${ZOOKEEPER_MEMORY_LIMITS}
        requests:
          cpu: ${ZOOKEEPER_CPU_REQUESTS}
          memory: ${ZOOKEEPER_MEMORY_REQUESTS}
      storage:
        deleteClaim: false
        size: ${ZK_VOL_SIZE}
        type: persistent-claim
