apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
  - max:
      cpu: 1500m
      memory: 6Gi
    min:
      cpu: 1m
      memory: 25Mi
    type: Pod
  - default:
      cpu: 100m
      memory: 500Mi
    defaultRequest:
      cpu: 20m
      memory: 50Mi
    maxLimitRequestRatio:
      cpu: "20"
    type: Container
