apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-non-terminating
  namespace: <>
spec:
  hard:
    limits.cpu: "12"
    limits.memory: 64Gi
    requests.cpu: "6"
    requests.memory: 32Gi
  scopes:
  - NotTerminating
